version: 2.1

.filter_all: &filter_all
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

.filter_tags: &filter_tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

.require_tests: &require_tests
  requires:
    - orb-tools/lint
    - orb-tools/pack

orbs:
  orb-tools: circleci/orb-tools@11.3.0
  shellcheck: circleci/shellcheck@3.1.2

workflows:
  continious:
    jobs:
      - orb-tools/lint:
          <<: *filter_all
      - orb-tools/pack:
          <<: *filter_all
      - orb-tools/publish-dev:
          <<: *require_tests
          orb-name: ${CIRCLE_PROJECT_USERNAME}/github-release
      - orb-tools/publish:
          <<: *require_tests
          <<: *filter_tags
          attach-workspace: true
          orb-ref: ${CIRCLE_PROJECT_USERNAME}/github-release@${CIRCLE_TAG}
