version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  shellcheck: circleci/shellcheck@2.0

workflows:
  continious:
    jobs:
      - orb-tools/lint:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - orb-tools/publish-dev:
          orb-name: timo-reymann/github-release
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - approve-prod-promote:
          type: approval
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - orb-tools/dev-promote-prod-from-git-tag:
          orb-name: timo-reymann/github-release
          add-pr-comment: false
          requires:
            - approve-prod-promote
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
