version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  shellcheck: circleci/shellcheck@2.0

workflows:
  continious:
    jobs:
      - orb-tools/lint:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - orb-tools/publish-dev:
          orb-name: timo-reymann/github-release
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-ref: timo-reymann/github-release@${CIRCLE_TAG}
          attach-workspace: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
