version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  shellcheck: circleci/shellcheck@2.0

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: timo-reymann/github-release
          requires: [hold-for-dev-publish]
