description: >
  Default executor using go 1.17
docker:
  - image: 'cimg/go:<<parameters.tag>>'
parameters:
  tag:
    default: 1.17
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/go/tags
    type: string
